version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_urp
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
