"""initial

Revision ID: 54f16321fdbb
Revises: 
Create Date: 2024-05-31 10:46:41.562133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54f16321fdbb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.UUID(as_uuid=True), primary_key=True, default=sa.text('uuid_generate_v4()'), unique=True),
        sa.Column('created_at', sa.DateTime, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime, server_default=sa.func.now(), server_onupdate=sa.func.now()),
        sa.Column('telegram_id', sa.BigInteger, unique=True, nullable=False),
        sa.Column('username', sa.String(32), nullable=True),
        sa.Column('first_name', sa.String(64), nullable=True),
        sa.Column('last_name', sa.String(64), nullable=True),
        sa.Column('phone_number', sa.String(25), nullable=True),
        sa.Column('language_code', sa.String(3), server_default='ru'),
        sa.Column('is_premium', sa.Boolean, server_default=sa.false(), nullable=True),
        sa.Column('is_blocked_by_user', sa.Boolean, server_default=sa.false(), nullable=False),
        sa.Column('has_message_distribution', sa.Boolean, server_default=sa.false(), nullable=False),
        sa.Column('is_setup_distribution', sa.Boolean, server_default=sa.false(), nullable=False),
        sa.Column('agreement_signed', sa.Boolean, server_default=sa.false(), nullable=False),
        sa.Column('is_admin', sa.Boolean, server_default=sa.false(), nullable=True),
        sa.Column('is_moderator', sa.Boolean, server_default=sa.false(), nullable=True),
        sa.Column('email', sa.String(254), unique=True, nullable=False),
        sa.Column('tab_namber', sa.Integer, unique=True, nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
