FROM python:3.11-slim

WORKDIR /app

COPY ./requirements_3.12.txt ./requirements.txt

RUN pip install --upgrade pip &&\
    pip install -r requirements.txt

COPY ./ ./


CMD ["alembic", "upgrade", "head"]
